.SUFFIX = .o .c

CC = cc 
CFLAG = -Wall -Werror -Wextra
NAME = pipex
LIBFT = ./ft_printf

SRC_F = errorhandling \
		find_path \
		redirect \
		pipe
		
B_OBJ_F = errorhandling find_path fork pipe utils
OBJS_DIR = bonus/
SRC = $(addsuffix .c, $(SRC_F))
OBJ = $(addsuffix .o, $(SRC_F))

B_SRC = $(addsuffix .c, $(B_SRC_F))
B_OBJ = $(addprefix $(OBJS_DIR), $(addsuffix .o, $(B_SRC_F)))
ifdef BONUS
		OBJ_F = $(B_OBJ)
else
		OBJ_F = $(OBJ)
endif

all : $(NAME)

$(OBJS_DIR):
		@mkdir -p $(OBJS_DIR)

$(NAME) :$(OBJSF) $(OBJ)
		make -C $(LIBFT)
		$(CC) $(CFLAG) -L $(LIBFT) -lprintft $^ -o $@

clean :
		make fclean -C $(LIBFT)
		rm -f $(OBJ)
		rm -f $(B_OBJ)

fclean : clean
	rm -f $(NAME)

re : fclean all

bonus : $(B_OBJ)
	make BONUS=1 all

.PHONY : all clean fclean re bonus